eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}

server:
  port: 8004

spring:
  profiles:
    active: ${BMS_PROFILE:development}
  config:
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:bms-mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:inventorydb}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:bms-rmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
    inventory-user:
      exchange: ${RABBITMQ_INVENTORY_USER_EXCHANGE:inventory-user-exchange}
      routing-key:
        remove-inventory-user: ${RABBITMQ_INVENTORY_USER_ROUTING_KEY:remove-inventory-user-key}
      queue:
        remove-inventory-user: ${RABBITMQ_INVENTORY_USER_QUEUE:remove-inventory-user-queue}
    cart-inventory:
      exchange: ${RABBITMQ_CART_INVENTORY_EXCHANGE:cart-inventory-exchange}
      routing-key:
        add-book-to-cart: ${RABBITMQ_CART_INVENTORY_ROUTING_KEY_ADD:ci-add-book-to-cart-rk}
        remove-book-from-cart: ${RABBITMQ_CART_INVENTORY_ROUTING_KEY_REMOVE:ci-remove-book-from-cart-rk}
      queue:
        add-book-to-cart: ${RABBITMQ_CART_INVENTORY_QUEUE_ADD:ci-add-book-to-cart-queue}
        remove-book-from-cart: ${RABBITMQ_CART_INVENTORY_QUEUE_REMOVE:ci-remove-book-from-cart-queue}

  redis:
    host: ${REDIS_HOST:bms-redis}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USER:user}
    password: ${REDIS_PASSWORD:password}

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"