eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}

server:
  port: 8001

spring:
  profiles:
    active: ${BMS_PROFILE:development} # Default to development if BMS_PROFILE is not set
  application:
    name: user-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888}  # Corrected config server URL
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:admin}:${MONGO_INITDB_ROOT_PASSWORD:admin}@bms-mongodb:27017/users?authSource=admin  # Complete MongoDB URI
      database: users 
  rabbitmq:
    host: bms-rmq # Use the service name defined in docker-compose
    port: 5672      # Use the correct port for RabbitMQ
    username: ${RABBITMQ_DEFAULT_USER:guest} # Default values if env vars are not set
    password: ${RABBITMQ_DEFAULT_PASS:guest}
    user-cart:
      exchange: user-cart-exchange 
      routing-key:
        delete-user: delete-user-rk
      queue:
        delete-user: delete-user-queue

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

jwt:
  secret: YourJWTSecretKey  # **IMPORTANT: Replace with your actual secret key**
  validity: 86400  # **IMPORTANT: Set the validity (e.g., in seconds)**